// ─── LEGACY (postojeći quest sistem) ─────────────────────────────────────────

export const DISCIPLINES_DATA = [
  { name: "Password Base", slug: "password-base", description: "Nauči kako da kreiraš jake lozinke, koristiš password manager i uključiš 2FA.", icon: "⌘", colorClass: "from-cyan/20 to-cyan/5 border-cyan/25", order: 1 },
  { name: "Phishing Harbor", slug: "phishing-harbor", description: "Prepoznaj phishing emailove, lažne login stranice i sumnjive linkove.", icon: "✉", colorClass: "from-violet/20 to-violet/5 border-violet/25", order: 2 },
  { name: "Privacy Zone", slug: "privacy-zone", description: "Zaštiti privatnost na društvenim mrežama i kontroliši šta dijeliš.", icon: "◉", colorClass: "from-green/20 to-green/5 border-green/25", order: 3 },
  { name: "Malware Lab", slug: "malware-lab", description: "Prepoznaj sumnjive priloge, USB uređaje i lažne aplikacije.", icon: "⚠", colorClass: "from-rose/20 to-rose/5 border-rose/25", order: 4 },
  { name: "Social Engineering Street", slug: "social-engineering", description: "Prepoznaj manipulaciju, lažne pozive i psihološke prevare.", icon: "⌬", colorClass: "from-amber/20 to-amber/5 border-amber/25", order: 5 },
  { name: "Final Cyber Challenge", slug: "final-challenge", description: "Kombinovani scenariji koji povezuju sve naučene oblasti.", icon: "▣", colorClass: "from-fuchsia/20 to-fuchsia/5 border-fuchsia/25", order: 6 },
];

export const QUESTS_DATA = [
  {
    disciplineSlug: "password-base",
    title: "Koja lozinka je najbezbjednija?",
    difficulty: "easy" as const,
    basePoints: 50,
    questType: "multiple_choice" as const,
    orderInDiscipline: 1,
    scenario: "Korisnik kreira nalog za novi online servis koji čuva važne finansijske dokumente.",
    taskText: "Izaberi najbezbjedniju lozinku.",
    hintText: "Dužina lozinke je često važnija od nasumičnog dodavanja jednog simbola.",
    feedbackCorrect: "Dobra lozinka treba da bude duga, jedinstvena i teško pogodiva. Fraze koje spajaju više nepovezanih riječi napadačima su mnogo teže za probijanje.",
    miniConclusion: "Duga passphrase sa kombinacijom nepovezanih riječi, brojeva i simbola je uvijek jača od kratke 'kompleksne' lozinke.",
    options: [
      { text: "marko123", isCorrect: false, explanation: "Ime i broj su prva kombinacija koju napadači pokušavaju.", order: 1 },
      { text: "Podgorica2024", isCorrect: false, explanation: "Grad i godina su predvidivi.", order: 2 },
      { text: "P@ssword!", isCorrect: false, explanation: "Ovaj šablon je uključen u sve liste za napad.", order: 3 },
      { text: "Rijeka-Kamen-73!Plava", isCorrect: true, explanation: "Duga, nepovezana fraza sa simbolima i brojevima — idealna lozinka.", order: 4 },
    ],
  },
  {
    disciplineSlug: "phishing-harbor",
    title: "Sumnjivi email od banke",
    difficulty: "medium" as const,
    basePoints: 70,
    questType: "decision" as const,
    orderInDiscipline: 1,
    scenario: "Korisniku stiže email od adrese 'support@bankovni-sistem-secure.net' sa naslovom 'HITNO: Vaš nalog je privremeno suspendovan'.",
    taskText: "Šta je najbezbjednija reakcija?",
    hintText: "Obrati pažnju na hitnost poruke, adresu pošiljaoca i zahtjev za unos osjetljivih podataka.",
    feedbackCorrect: "Phishing poruke gotovo uvijek koriste pritisak i hitnost. Legitimna banka nikad ne traži da unosiš podatke kartice preko linka iz emaila.",
    miniConclusion: "Sumnjivim emailovima nikad ne klikaj na linkove — idi direktno na zvanični sajt.",
    options: [
      { text: "Odmah kliknuti link jer poruka izgleda hitno", isCorrect: false, explanation: "Upravo na to napadači računaju — hitnost i lažni autoritet su osnova phishinga.", order: 1 },
      { text: "Odgovoriti na email i tražiti objašnjenje", isCorrect: false, explanation: "Odgovaranjem potvrđuješ napadaču da je adresa aktivna.", order: 2 },
      { text: "Ne klikati link, provjeriti adresu pošiljaoca i otvoriti banku direktno", isCorrect: true, explanation: "Ovo je jedina bezbjedna reakcija.", order: 3 },
      { text: "Proslijediti email prijatelju da provjeri", isCorrect: false, explanation: "Prosljeđivanjem širiš potencijalnu phishing poruku.", order: 4 },
    ],
  },
  {
    disciplineSlug: "privacy-zone",
    title: "Avionska karta na Instagramu",
    difficulty: "easy" as const,
    basePoints: 45,
    questType: "risk_assessment" as const,
    orderInDiscipline: 1,
    scenario: "Korisnik se sprema za putovanje i želi da objavi fotografiju avionske karte na Instagram story.",
    taskText: "Koji je najveći bezbjednosni rizik?",
    hintText: "Razmisli koji konkretni podaci se nalaze na avionskoj karti, osim datuma i destinacije.",
    feedbackCorrect: "Avionska karta sadrži ime, broj leta, kod rezervacije i bar kod. Kod rezervacije može biti iskorišćen za pristup tvojoj rezervaciji.",
    miniConclusion: "Osjetljive podatke zamaži ili sakrij prije objave.",
    options: [
      { text: "Nema rizika — story traje samo 24 sata", isCorrect: false, explanation: "Story može biti screenshotovan odmah.", order: 1 },
      { text: "Na karti se nalaze lični podaci i kod rezervacije koji mogu biti zloupotrijebljeni", isCorrect: true, explanation: "Kod rezervacije može otvoriti pristup cijeloj rezervaciji.", order: 2 },
      { text: "Rizik postoji samo ako je Instagram profil javan", isCorrect: false, explanation: "I pratioci mogu odmah napraviti screenshot.", order: 3 },
      { text: "Nema problema ako se prekrije samo lice", isCorrect: false, explanation: "Lice nije problem — problem su kodovi na karti.", order: 4 },
    ],
  },
  {
    disciplineSlug: "malware-lab",
    title: "Sumnjivi prilog u emailu",
    difficulty: "medium" as const,
    basePoints: 70,
    questType: "decision" as const,
    orderInDiscipline: 1,
    scenario: "Korisnik dobija email od adrese 'delivery@courier-fast-rs.net' sa prilogom 'Faktura_2026.exe'.",
    taskText: "Šta treba uraditi sa ovim emailom i prilogom?",
    hintText: "Obrati pažnju na ekstenziju fajla. Šta rade .exe fajlovi?",
    feedbackCorrect: "Izvršni fajlovi (.exe) mogu pokrenuti bilo koji kod na računaru. Faktura nikad ne bi trebalo da bude .exe — to bi trebalo biti PDF.",
    miniConclusion: ".exe od nepoznatog pošiljaoca = ne otvarati nikad. Legitimne fakture dolaze kao PDF.",
    options: [
      { text: "Otvoriti fajl — vjerovatno je zaista faktura", isCorrect: false, explanation: "Otvaranje .exe fajla od nepoznate adrese može odmah zaraziti računar malwareom.", order: 1 },
      { text: "Ne otvarati prilog, provjeriti pošiljaoca i obrisati/prijaviti email", isCorrect: true, explanation: "Sumnjiv .exe od nepoznatog pošiljaoca se ne otvara — najbezbjednije je ne dirati prilog, provjeriti pošiljaoca i prijaviti poruku kao spam.", order: 2 },
      { text: "Preimenovati fajl iz .exe u .pdf i tada ga otvoriti", isCorrect: false, explanation: "Preimenovanje ne mijenja sadržaj fajla.", order: 3 },
      { text: "Proslijediti fajl kolegi da on provjeri", isCorrect: false, explanation: "Prosljeđivanjem potencijalnog malwarea ugrožavaš kolegu.", order: 4 },
    ],
  },
  {
    disciplineSlug: "social-engineering",
    title: "Prijatelj koji traži novac",
    difficulty: "medium" as const,
    basePoints: 70,
    questType: "decision" as const,
    orderInDiscipline: 1,
    scenario: "Korisnik dobija Instagram poruku od profila prijatelja: 'Hej, ukraden mi je novčanik. Možeš li mi hitno poslati 50 €?'",
    taskText: "Koja reakcija je najbezbjednija?",
    hintText: "Social engineering napadi računaju na hitnost i emocionalni odgovor.",
    feedbackCorrect: "Kompromitovani nalozi na društvenim mrežama se veoma često koriste za ovakve prevare. Uvijek provjeri identitet osobe drugim kanalom.",
    miniConclusion: "Hitni zahtjevi za novcem ili podacima = uvijek provjeri identitet drugim kanalom.",
    options: [
      { text: "Odmah poslati novac — to je prijatelj u nevolji", isCorrect: false, explanation: "Hitnost je glavno oruđe social engineeringa.", order: 1 },
      { text: "Tražiti broj računa i poslati manji iznos kao provjeru", isCorrect: false, explanation: "Čak i manji iznos pomaže napadaču.", order: 2 },
      { text: "Kontaktirati prijatelja pozivom ili SMS-om na poznati broj", isCorrect: true, explanation: "Jedini bezbjedan korak je da provjeriš identitet putem kanala koji već znaš.", order: 3 },
      { text: "Objaviti screenshot na sopstvenom story-u", isCorrect: false, explanation: "Objava bez provjere može biti nepravična.", order: 4 },
    ],
  },
];

export const BADGES_DATA = [
  { name: "Password Protector", slug: "password-protector", description: "Završio/la sve misije iz Password Base discipline.", icon: "🔐", conditionType: "discipline_complete" as const, conditionValue: "password-base" },
  { name: "Phishing Hunter", slug: "phishing-hunter", description: "Završio/la sve misije iz Phishing Harbor discipline.", icon: "🎣", conditionType: "discipline_complete" as const, conditionValue: "phishing-harbor" },
  { name: "Privacy Guardian", slug: "privacy-guardian", description: "Završio/la sve misije iz Privacy Zone discipline.", icon: "🛡️", conditionType: "discipline_complete" as const, conditionValue: "privacy-zone" },
  { name: "Malware Defender", slug: "malware-defender", description: "Završio/la sve misije iz Malware Lab discipline.", icon: "🦠", conditionType: "discipline_complete" as const, conditionValue: "malware-lab" },
  { name: "Mind Guard", slug: "mind-guard", description: "Završio/la sve misije iz Social Engineering Street discipline.", icon: "🧠", conditionType: "discipline_complete" as const, conditionValue: "social-engineering" },
  { name: "No Hint Hero", slug: "no-hint-hero", description: "Završio/la misiju bez korišćenja hinta.", icon: "⚡", conditionType: "no_hint" as const, conditionValue: null },
  { name: "Perfect Mission", slug: "perfect-mission", description: "Završio/la misiju sa maksimalnim rezultatom.", icon: "🏆", conditionType: "perfect_score" as const, conditionValue: null },
  { name: "Cyber Guardian", slug: "cyber-guardian", description: "Završio/la sve dostupne misije.", icon: "🌐", conditionType: "all_complete" as const, conditionValue: null },
  { name: "First Steps", slug: "first-steps", description: "Završio/la prvih 5 misija.", icon: "👣", conditionType: "quests_count" as const, conditionValue: "5" },
];

// ─── NOVI GAME SISTEM ─────────────────────────────────────────────────────────

export const GAME_BADGES_DATA = [
  { name: "Prvi korak", slug: "prvi-korak", description: "Završio/la prvi scenarij u igri.", icon: "🎯", conditionType: "quests_count" as const, conditionValue: "1" },
  { name: "Lovac na phishing", slug: "lovac-na-phishing", description: "Završio/la sve phishing scenarije.", icon: "🎣", conditionType: "discipline_complete" as const, conditionValue: "phishing" },
  { name: "Kovač lozinki", slug: "kovac-lozinki", description: "Završio/la sve scenarije o lozinkama.", icon: "⚒️", conditionType: "discipline_complete" as const, conditionValue: "lozinke" },
  { name: "Bez greške", slug: "bez-greske", description: "Završio/la temu sa 100% tačnih odgovora.", icon: "💎", conditionType: "perfect_score" as const, conditionValue: null },
  { name: "Niz od 7", slug: "niz-od-7", description: "7 dana zaredom aktivan/na.", icon: "🔥", conditionType: "quests_count" as const, conditionValue: "7" },
  { name: "Mrežni Čuvar", slug: "mrezni-cuvar", description: "Dostigao/la Level 9.", icon: "🛡️", conditionType: "all_complete" as const, conditionValue: null },
  { name: "Brze ruke", slug: "brze-ruke", description: "Završio/la Brzi krug za manje od 30 sekundi.", icon: "⚡", conditionType: "no_hint" as const, conditionValue: null },
  { name: "Sveznalica", slug: "sveznalica", description: "Završio/la bar jednu misiju iz svake teme.", icon: "🧠", conditionType: "all_complete" as const, conditionValue: null },
  { name: "Oprezni", slug: "oprezni", description: "Prepoznao/la 20 cyber prijetnji.", icon: "👁️", conditionType: "quests_count" as const, conditionValue: "20" },
  { name: "Postojan", slug: "postojan", description: "Učestvovao/la u 30 dnevnih izazova.", icon: "🏆", conditionType: "quests_count" as const, conditionValue: "30" },
];

export const GAME_TOPICS_DATA = [
  {
    slug: "akademija",
    name: "Akademija",
    opis: "Početak putanje — osnove sajber bezbjednosti uz Bajta. Uvijek dostupno za vježbu.",
    lekcija: "Dobrodošao u Akademiju Sajber Čuvara. Ovdje vježbaš osnove: prepoznavanje mamaca, pravljenje jakih lozinki, uočavanje lažnih linkova i dvofaktorsku zaštitu. Pravilo broj jedan: stani i pomisli sekundu prije nego što klikneš. Ova pitanja su uvijek tu — vrati se kad god želiš da osvježiš osnove.",
    ikona: "★",
    colorClass: "from-orange/20 to-orange/5 border-orange/25",
    order: 9,
  },
  {
    slug: "lozinke",
    name: "Lozinke",
    opis: "Nauči kako da kreiraš jake lozinke i upravljaš njima bezbjedno.",
    lekcija: "Jaka lozinka je duga, jedinstvena i nasumična. Koristi password manager da za svaki nalog imaš posebnu lozinku. Nikad ne ponavljaj lozinke — jedan kompromitovani nalog ne smije ugroziti sve ostale.",
    ikona: "🔑",
    colorClass: "from-cyan/20 to-cyan/5 border-cyan/25",
    order: 10,
  },
  {
    slug: "phishing",
    name: "Phishing",
    opis: "Prepoznaj lažne emailove, SMS poruke i sajtove koji kradu podatke.",
    lekcija: "Phishing napadi koriste hitnost, strah i imitaciju poznatih brendova. Uvijek provjeri pravu adresu pošiljaoca i nikad ne kuckaj lozinku kroz link iz poruke — otvori sajt ručno. Legitiman servis nikad ne traži hitne akcije putem emaila.",
    ikona: "🎣",
    colorClass: "from-violet/20 to-violet/5 border-violet/25",
    order: 11,
  },
  {
    slug: "privatnost",
    name: "Privatnost",
    opis: "Kontroliši šta dijeliš na internetu i zaštiti lične podatke.",
    lekcija: "Svaki podatak koji objaviš online ostaje tamo zauvijek. Provjeri dozvole aplikacija i daj im samo minimalan pristup. Privatnost nije paranoja — to je osnovna digitalna higijena.",
    ikona: "🕵️",
    colorClass: "from-green/20 to-green/5 border-green/25",
    order: 12,
  },
  {
    slug: "malver",
    name: "Malware",
    opis: "Prepoznaj maliciozni softver i zaštiti uređaj od infekcija.",
    lekcija: "Malware često dolazi kroz zaražene fajlove, lažne aplikacije i sumnjive linkove. Nikad ne otvaraj .exe fajlove od nepoznatih pošiljalaca. Redovan backup podataka je najbolja zaštita ako te pogodi ransomware.",
    ikona: "🦠",
    colorClass: "from-rose/20 to-rose/5 border-rose/25",
    order: 13,
  },
  {
    slug: "javni-wifi",
    name: "Javni Wi-Fi",
    opis: "Koristi javne Wi-Fi mreže oprezno i zaštiti podatke u pokretu.",
    lekcija: "Na javnom Wi-Fi-ju neko može presretati saobraćaj. Za osjetljive radnje — bankarstvo, email, prijave — koristi mobilne podatke ili VPN. Ne šalji lozinke i podatke kartice preko otvorene mreže.",
    ikona: "📡",
    colorClass: "from-amber/20 to-amber/5 border-amber/25",
    order: 14,
  },
  {
    slug: "dvofaktorska",
    name: "Dvofaktorska zaštita",
    opis: "Dodaj drugi sloj zaštite na sve važne naloge.",
    lekcija: "Dvofaktorska autentifikacija znači da napadač ne može ući samo sa lozinkom. Authenticator app je bezbjedniji od SMS-a jer ne zavisi od mobilne mreže. Uključi 2FA gdje god je dostupna.",
    ikona: "🔐",
    colorClass: "from-blue/20 to-blue/5 border-blue/25",
    order: 15,
  },
  {
    slug: "socijalni-inzenjering",
    name: "Socijalni inženjering",
    opis: "Prepoznaj psihološku manipulaciju i lažne identitete online.",
    lekcija: "Socijalni inženjering iskorišćava povjerenje, hitnost i autoritet. Napadači se pretvaraju da su IT podrška, menadžeri ili prijatelji u nevolji. Uvijek provjeri identitet kroz drugi kanal prije nego što dijeliš podatke ili novac.",
    ikona: "🎭",
    colorClass: "from-pink/20 to-pink/5 border-pink/25",
    order: 16,
  },
  {
    slug: "prevare",
    name: "Online prevare",
    opis: "Prepoznaj uobičajene online prevare i zaštiti sebe i novac.",
    lekcija: "Ako nešto zvuči previše dobro da bi bilo istinito — vjerovatno jeste prevara. Lažne nagradne igre, investicijske sheme i online prodavnice kradu novac i podatke. Provjeri legitimnost svake stranice prije unosa podataka kartice.",
    ikona: "⚠️",
    colorClass: "from-orange/20 to-orange/5 border-orange/25",
    order: 17,
  },
  {
    slug: "azuriranja",
    name: "Ažuriranja softvera",
    opis: "Drži sistem i aplikacije ažurnim zbog bezbjednosti.",
    lekcija: "Bezbjednosna ažuriranja krpe rupe kroz koje napadači ulaze u sistem. Zastarjeli softver je čest ulaz za malware i napade. Uključi automatska ažuriranja i primijeni ih što prije — ne odgađaj.",
    ikona: "🔄",
    colorClass: "from-teal/20 to-teal/5 border-teal/25",
    order: 18,
  },
  {
    slug: "sigurno-preuzimanje",
    name: "Bezbjedno preuzimanje",
    opis: "Preuzimaj softver samo iz provjerenih izvora.",
    lekcija: "Lažne aplikacije i piratski softver često sadrže malware. Uvijek preuzimaj iz zvanične prodavnice (App Store, Google Play) ili direktno sa stranice proizvođača. Provjeri recenzije i dozvole aplikacije prije instalacije.",
    ikona: "⬇️",
    colorClass: "from-indigo/20 to-indigo/5 border-indigo/25",
    order: 19,
  },
];

// Tip-ovi interakcija:
// odluka, phishing_inbox, lozinka, razvrstaj, pravo_lazno, razgovor, podesi, brzi_krug

export const SCENARIOS_DATA = [
  // ═══════════════════════════════════════════════════════════════════
  // 0. AKADEMIJA (uvodna pitanja — uvijek dostupna)
  // ═══════════════════════════════════════════════════════════════════
  {
    topicSlug: "akademija",
    title: "Prvi mamac",
    interactionType: "odluka",
    difficulty: "easy",
    xp: 40,
    order: 1,
    tekst: "Bajt te uvodi u Akademiju. Na ekranu iskoči poruka: „Izabran si za nagradu od 10.000 €! Klikni ODMAH da preuzmeš!“ Šta radiš?",
    hint: "Zapitaj se: zašto bi ti neko poklonio 10.000 € bez razloga?",
    objasnjenje: "Predobra ponuda + hitnost + zahtjev da odmah klikneš = klasičan mamac. Pravi pokloni te ne jure sa tajmerom. Kad nešto zvuči predobro da bi bilo istinito, najčešće i jeste prevara. Stani i pomisli sekundu prije klika.",
    gameData: {
      opcije: [
        { id: "a", tekst: "Kliknem odmah — ko bi propustio 10.000 €!" },
        { id: "b", tekst: "Ignorišem — niko ne dijeli 10.000 € bez razloga." },
        { id: "c", tekst: "Unesem svoje podatke da provjerim je li stvarno." },
        { id: "d", tekst: "Proslijedim poruku prijateljima da i oni dobiju nagradu." },
      ],
    },
    correctData: { id: "b" },
  },
  {
    topicSlug: "akademija",
    title: "Tvoja prva lozinka",
    interactionType: "odluka",
    difficulty: "easy",
    xp: 40,
    order: 2,
    tekst: "Praviš prvu lozinku za svoj nalog u Akademiji. Koja je od ovih najbezbjednija?",
    hint: "Dužina i nepovezane riječi jače su od kratke „komplikovane“ lozinke.",
    objasnjenje: "Duga fraza od nepovezanih riječi teža je za probijanje od kratke lozinke s par simbola. Imena, datumi i „lozinka123“ prve su kombinacije koje napadači probaju. Pravilo: što duže i nepredvidivije, to bolje — i koristi jedinstvenu lozinku za svaki nalog.",
    gameData: {
      opcije: [
        { id: "a", tekst: "marko2005" },
        { id: "b", tekst: "lozinka123" },
        { id: "c", tekst: "konj-baterija-spajalica-7" },
        { id: "d", tekst: "12345678" },
      ],
    },
    correctData: { id: "c" },
  },
  {
    topicSlug: "akademija",
    title: "Koji link je pravi?",
    interactionType: "odluka",
    difficulty: "easy",
    xp: 40,
    order: 3,
    tekst: "Dobiješ poruku s linkom za prijavu na nalog Akademije. Koji link je pravi i siguran?",
    hint: "Pažljivo pročitaj cijeli domen — slovo po slovo, naročito ono ispred prve kose crte.",
    objasnjenje: "Lažni linkovi mijenjaju slova (1 umjesto i), dodaju riječi (-verify, -secure) ili koriste čudne ekstenzije (.tk, .xyz). Pravi domen je ono što stoji neposredno ispred prve „/“. Kad sumnjaš — ne klikaj, nego ručno otvori zvaničnu stranicu.",
    gameData: {
      opcije: [
        { id: "a", tekst: "https://akademija-cuvara.rs/prijava" },
        { id: "b", tekst: "http://akademija-cuvara-verify.tk/login" },
        { id: "c", tekst: "https://akadem1ja-cuvara.rs/prijava" },
        { id: "d", tekst: "http://akademija.login-sada.xyz" },
      ],
    },
    correctData: { id: "a" },
  },
  {
    topicSlug: "akademija",
    title: "Drugi sloj zaštite",
    interactionType: "odluka",
    difficulty: "easy",
    xp: 40,
    order: 4,
    tekst: "Bajt ti predlaže da uključiš dvofaktorsku zaštitu (2FA). Šta je tačno o 2FA?",
    hint: "Šta se desi ako neko sazna tvoju lozinku, a ti imaš uključen i drugi faktor?",
    objasnjenje: "2FA dodaje drugi sloj — kod iz aplikacije ili poruke koji samo ti imaš. I ako napadač sazna lozinku, bez drugog faktora ne može da uđe. Authenticator app je bezbjedniji od SMS-a. Uključi 2FA gdje god je dostupna.",
    gameData: {
      opcije: [
        { id: "a", tekst: "Nepotrebna je ako imam jaku lozinku." },
        { id: "b", tekst: "Traži drugi korak pri prijavi, pa napadač ne može ući samo sa lozinkom." },
        { id: "c", tekst: "Usporava prijavu i ne donosi nikakvu korist." },
        { id: "d", tekst: "Znači da svoju lozinku mogu mirno dijeliti s prijateljima." },
      ],
    },
    correctData: { id: "b" },
  },

  // ═══════════════════════════════════════════════════════════════════
  // 1. LOZINKE
  // ═══════════════════════════════════════════════════════════════════
  {
    topicSlug: "lozinke",
    title: "Koja lozinka je najbezbjednija?",
    interactionType: "odluka",
    difficulty: "easy",
    xp: 50,
    order: 1,
    tekst: "Tvoj prijatelj kreira nalog za online bankarstvo i traži savjet. Koja od ovih lozinki je zaista bezbjedna?",
    hint: "Razmisli o dužini, nasumičnosti i jedinstvenosti.",
    objasnjenje: "Duga fraza od nepovezanih nasumičnih riječi je teža za probijanje od kratke 'komplikovane' lozinke. Dužina je važnija od simbola. Idealno: jedinstvena lozinka po nalogu uz menadžer lozinki.",
    gameData: {
      opcije: [
        { id: "a", tekst: "bojan123" },
        { id: "b", tekst: "Ljeto2024!" },
        { id: "c", tekst: "konj-baterija-spajalica-7" },
        { id: "d", tekst: "password" },
      ],
    },
    correctData: { id: "c" },
  },
  {
    topicSlug: "lozinke",
    title: "Iskuj svoju lozinku",
    interactionType: "lozinka",
    difficulty: "easy",
    xp: 60,
    order: 2,
    tekst: "Napravi lozinku koja dostigne ocjenu 'jaka'. Moraš ispuniti sve kriterijume.",
    hint: "Kombinuj malo i veliko slovo, broj i simbol — i neka bude duga.",
    objasnjenje: "Snaga raste s dužinom i raznovrsnošću znakova. Izbjegavaj imena, datume rođenja i riječi iz rječnika — njih napadači probaju prve. Passphrase od više nepovezanih riječi je lak za pamćenje, a jak za zaštitu.",
    gameData: {
      kriteriji: [
        { id: "k1", tekst: "Najmanje 12 znakova", regex: ".{12,}" },
        { id: "k2", tekst: "Malo slovo (a-z)", regex: "[a-z]" },
        { id: "k3", tekst: "Veliko slovo (A-Z)", regex: "[A-Z]" },
        { id: "k4", tekst: "Broj (0-9)", regex: "\\d" },
        { id: "k5", tekst: "Simbol (!@#$%^&*)", regex: "[^a-zA-Z0-9]" },
      ],
      zabranjene: ["password", "lozinka", "123456", "qwerty", "abc123"],
    },
    correctData: { minScore: 80 },
  },
  {
    topicSlug: "lozinke",
    title: "Menadžer lozinki ili ista lozinka?",
    interactionType: "pravo_lazno",
    difficulty: "medium",
    xp: 65,
    order: 3,
    tekst: "Koji od ovih savjeta je ispravan? Odaberi pravi!",
    hint: "Razmisli šta se desi kada jedan servis 'procuri' listu lozinki.",
    objasnjenje: "Čak i najjača lozinka postaje opasna ako je koristiš na više mjesta. Jedan kompromitovani servis → svi tvoji nalozi ugroženi. Menadžer lozinki rješava oba problema: pamti i generiše jedinstvene jake lozinke.",
    gameData: {
      tip: "savjet",
      uputstvo: "Koji savjet je ispravan?",
      a: { tekst: "Menadžer lozinki pamti i generiše jake, jedinstvene lozinke za svaki servis.", oznaka: "A" },
      b: { tekst: "Koristi istu jaku lozinku na svim servisima — lakše pamtiš i jednako si zaštićen.", oznaka: "B" },
    },
    correctData: { tacno: "a" },
  },

  // ═══════════════════════════════════════════════════════════════════
  // 2. PHISHING
  // ═══════════════════════════════════════════════════════════════════
  {
    topicSlug: "phishing",
    title: "Phishing email od PayPal-a",
    interactionType: "phishing_inbox",
    difficulty: "medium",
    xp: 70,
    order: 1,
    tekst: "Prikazan je email koji si primio/la. Tapni sve crvene zastavice — znakove da je ovo phishing!",
    hint: "Provjeri adresu pošiljaoca, naslov, tijelo poruke i link.",
    objasnjenje: "Phishing koristi hitnost i strah da te natjera na brzu reakciju. Provjeri pravi domen pošiljaoca — 'paypa1' (sa jedinicom umjesto slova l) nije PayPal. Nikad ne unosi lozinku preko linka iz poruke — otvori sajt ručno.",
    gameData: {
      od: "support@paypa1-secure.com",
      naslov: "HITNO: Vaš nalog će biti zaključan za 24h!!!",
      tijelo: "Poštovani korisniče,\n\nPrimijetili smo sumnjive aktivnosti na Vašem PayPal nalogu. Molimo Vas da odmah potvrdite svoje podatke kako bi izbegli trajno blokiranje naloga.\n\nVaš nalog će biti ZAKLJUČAN za 24 sata ako ne preduzmete hitne mjere.\n\nKliknite ovdje da potvrdite:\nhttp://paypal-verify.tk/login\n\nPayPal Tim za bezbjednost",
      link: "http://paypal-verify.tk/login",
      zastavice: [
        { id: "z1", tekst: "Lažni domen u email adresi (paypa1 umjesto paypal)", element: "od" },
        { id: "z2", tekst: "Vještačka hitnost i prijetnja blokiranjem", element: "naslov" },
        { id: "z3", tekst: "Sumnjiv link sa .tk domenom", element: "link" },
        { id: "z4", tekst: "Greška u pravopisu (izbegli umjesto izbjegli)", element: "tijelo" },
      ],
    },
    correctData: { ids: ["z1", "z2", "z3", "z4"] },
  },
  {
    topicSlug: "phishing",
    title: "Pravi ili lažni Facebook?",
    interactionType: "pravo_lazno",
    difficulty: "easy",
    xp: 55,
    order: 2,
    tekst: "Dobio/la si link u poruci. Koja od ove dvije adrese vodi na pravi Facebook?",
    hint: "Pažljivo pročitaj svaki karakter u domenu.",
    objasnjenje: "Lažni domeni mijenjaju slova (0 umjesto o, l umjesto I), dodaju riječi ('-login','-secure') ili koriste čudne ekstenzije. Pažljivo pročitaj cijeli domen prije unosa podataka. Čak jedan pogrešan karakter znači da si na lažnoj stranici.",
    gameData: {
      tip: "url",
      uputstvo: "Koja adresa vodi na pravi Facebook?",
      a: { tekst: "https://www.facebook.com/login", oznaka: "A" },
      b: { tekst: "https://www.faceb00k-login.com", oznaka: "B" },
    },
    correctData: { tacno: "a" },
  },
  {
    topicSlug: "phishing",
    title: "Brzi test: Phishing znakovi",
    interactionType: "brzi_krug",
    difficulty: "medium",
    xp: 80,
    order: 3,
    tekst: "Imaš 45 sekundi! Odgovori na sva pitanja o prepoznavanju phishinga što brže možeš.",
    hint: "Nemoj razmišljati predugo — pročitaj svako pitanje i biraj instinktivno.",
    objasnjenje: "Brzo prepoznavanje phishinga je vještina — što više vježbaš, to lakše uočavaš crvene zastavice. Ključni znakovi su lažni domen, hitnost, zahtjev za podacima i greške u tekstu.",
    gameData: {
      vrijemeSekundi: 45,
      pitanja: [
        {
          tekst: "Koji domen je lažan?",
          opcije: ["paypal.com", "paypa1.com", "paypal.net", "paypal.org"],
          tacno: 1,
        },
        {
          tekst: "Šta je tipičan znak phishing emaila?",
          opcije: ["Ime pošiljaoca", "Vještačka hitnost i prijetnja", "Dug tekst", "Prilog .pdf"],
          tacno: 1,
        },
        {
          tekst: "Šta nikad ne treba da uradiš ako primiš sumnjivi email?",
          opcije: ["Prijaviti kao spam", "Kliknuti link i provjeriti", "Obrisati email", "Kontaktirati podršku direktno"],
          tacno: 1,
        },
        {
          tekst: "Legitiman servis NIKAD ne traži...",
          opcije: ["Potvrdu emaila", "Lozinku ili PIN putem emaila", "Ažuriranje profila", "Plaćanje računa"],
          tacno: 1,
        },
        {
          tekst: "Koji link je siguran?",
          opcije: ["http://banka-secure.tk/login", "https://banka.rs/login", "banka-login.com", "http://198.51.100.1/login"],
          tacno: 1,
        },
      ],
    },
    correctData: { tacni: [1, 1, 1, 1, 1] },
  },

  // ═══════════════════════════════════════════════════════════════════
  // 3. PRIVATNOST
  // ═══════════════════════════════════════════════════════════════════
  {
    topicSlug: "privatnost",
    title: "Šta je bezbjedno podijeliti?",
    interactionType: "razvrstaj",
    difficulty: "easy",
    xp: 55,
    order: 1,
    tekst: "Razvrstaj stavke u dvije kategorije: šta je bezbjedno dijeliti online, a šta je rizično?",
    hint: "Razmisli ko može vidjeti ovu informaciju i kako bi je mogao zloupotrijebiti.",
    objasnjenje: "Svaki podatak koji objaviš online može biti viđen, snimljen i zloupotrijebljen. Datum rođenja, kućna adresa i broj telefona su zlatna ruda za identitetsku krađu. Dijeli samo ono što bi pokazao potpunom strancu na ulici.",
    gameData: {
      stavke: [
        { id: "s1", tekst: "Naziv omiljene knjige" },
        { id: "s2", tekst: "Kućna adresa" },
        { id: "s3", tekst: "Fotografija jela u restoranu" },
        { id: "s4", tekst: "Tačan datum i sat povratka s odmora" },
        { id: "s5", tekst: "Broj telefona na javnom profilu" },
        { id: "s6", tekst: "Profesionalne vještine na LinkedIn-u" },
      ],
      kante: [
        { id: "sigurno", naziv: "Bezbjedno ✓" },
        { id: "rizicno", naziv: "Rizično ✗" },
      ],
    },
    correctData: {
      sigurno: ["s1", "s3", "s6"],
      rizicno: ["s2", "s4", "s5"],
    },
  },
  {
    topicSlug: "privatnost",
    title: "Privatnost na pametnom telefonu",
    interactionType: "podesi",
    difficulty: "easy",
    xp: 60,
    order: 2,
    tekst: "Podesi privatnost na pametnom telefonu. Uključi ono što povećava privatnost, isključi ono što je smanjuje.",
    hint: "Manje dozvola = manje podataka koje aplikacije skupljaju.",
    objasnjenje: "Aplikacije skupljaju daleko više podataka nego što im treba. Lokacija u pozadini je rijetko potrebna. Reklamni ID možeš resetovati da ograničiš praćenje. Korisno je redovno provjeravati postavke privatnosti.",
    gameData: {
      uputstvo: "Postavi bezbjedne opcije privatnosti.",
      opcije: [
        { id: "o1", naziv: "Lokacija samo kada koristim aplikaciju", opis: "Aplikacije ne prate lokaciju u pozadini", ikona: "📍", tacnoStanje: true },
        { id: "o2", naziv: "Lokacija uvijek (i u pozadini)", opis: "Aplikacije prate lokaciju stalno", ikona: "🗺️", tacnoStanje: false },
        { id: "o3", naziv: "Resetuj reklamni ID", opis: "Ograničava praćenje za reklame", ikona: "🎯", tacnoStanje: true },
        { id: "o4", naziv: "Dijeli analitiku s programerima", opis: "Šalje podatke o korišćenju aplikacija", ikona: "📊", tacnoStanje: false },
      ],
    },
    correctData: { ukljuceno: ["o1", "o3"], iskljuceno: ["o2", "o4"] },
  },
  {
    topicSlug: "privatnost",
    title: "Fotografija iz odmora",
    interactionType: "odluka",
    difficulty: "easy",
    xp: 50,
    order: 3,
    tekst: "Upravo si stigao/la na odmor i hoćeš da objavljuješ slike. Koja praksa je najbezbjednija za tebe i tvoj dom?",
    hint: "Razmisli ko zna da nisi kod kuće ako objavljuješ u realnom vremenu.",
    objasnjenje: "Objava lokacije u realnom vremenu govori pratiocima — i potencijalnim lopovima — da nisi kod kuće. Bezbjednije je dijeliti uspomene nakon povratka, bez preciznih geotagova. Privatni profil ne znači automatski da si zaštićen/a.",
    gameData: {
      opcije: [
        { id: "a", tekst: "Objavljujem sve slike odmah s tačnom lokacijom" },
        { id: "b", tekst: "Objavljujem slike nakon povratka, bez precizne lokacije" },
        { id: "c", tekst: "Objavljujem na privatnom profilu odmah — ionako imam malo pratilaca" },
        { id: "d", tekst: "Ne objavljujem nikad ništa" },
      ],
    },
    correctData: { id: "b" },
  },

  // ═══════════════════════════════════════════════════════════════════
  // 4. MALVER
  // ═══════════════════════════════════════════════════════════════════
  {
    topicSlug: "malver",
    title: "Email prilog .exe",
    interactionType: "odluka",
    difficulty: "medium",
    xp: 65,
    order: 1,
    tekst: "Primio/la si email od nepoznatog pošiljaoca sa prilogom 'Faktura_2026.exe'. Šta radiš?",
    hint: "Koje vrste fajlova mogu pokretati programe na računaru?",
    objasnjenje: ".exe fajlovi su izvršni programi i mogu pokrenuti bilo koji kod na računaru. Legitimna faktura dolazi kao PDF, ne kao .exe. Napadači često sakriju malware iza naziva koji liči na običan dokument.",
    gameData: {
      opcije: [
        { id: "a", tekst: "Otvorim prilog — vjerovatno je zaista faktura" },
        { id: "b", tekst: "Preimenujem ga iz .exe u .pdf pa ga otvaram" },
        { id: "c", tekst: "Provjerim pošiljaoca, ne otvorim prilog i prijavim kao spam" },
        { id: "d", tekst: "Proslijedim kolegi da provjeri" },
      ],
    },
    correctData: { id: "c" },
  },
  {
    topicSlug: "malver",
    title: "Bezbjedno ili rizično preuzimanje",
    interactionType: "razvrstaj",
    difficulty: "medium",
    xp: 70,
    order: 2,
    tekst: "Razvrstaj načine preuzimanja softvera na bezbjedne i rizične.",
    hint: "Zvanični izvori imaju sistem provjere aplikacija. Torrent i nepoznati sajtovi — nemaju.",
    objasnjenje: "Malware se često širi kroz piratski softver i aplikacije iz nezvaničnih izvora. Zvanične prodavnice (App Store, Google Play, Microsoft Store) ne uklanjaju svaki rizik, ali ga značajno smanjuju. Kad možeš, preuzimaj direktno od proizvođača.",
    gameData: {
      stavke: [
        { id: "s1", tekst: "Preuzimanje s Google Play" },
        { id: "s2", tekst: "Torrent fajl s piratske stranice" },
        { id: "s3", tekst: "Direktno sa zvanične stranice proizvođača" },
        { id: "s4", tekst: "APK fajl s nepoznatog foruma" },
        { id: "s5", tekst: "Preuzimanje s Microsoft Store" },
        { id: "s6", tekst: "Softver 'besplatno' s cracking sajta" },
      ],
      kante: [
        { id: "sigurno", naziv: "Bezbjedno ✓" },
        { id: "rizicno", naziv: "Rizično ✗" },
      ],
    },
    correctData: {
      sigurno: ["s1", "s3", "s5"],
      rizicno: ["s2", "s4", "s6"],
    },
  },
  {
    topicSlug: "malver",
    title: "Brzi test: Malware znanje",
    interactionType: "brzi_krug",
    difficulty: "medium",
    xp: 75,
    order: 3,
    tekst: "Brzi krug! Imaš 40 sekundi da odgovoriš na pitanja o zaštiti od malwarea.",
    hint: "Fokusiraj se na osnove: vrste malwarea, kako se širi i kako se štitiš.",
    objasnjenje: "Malware je opšti naziv za zlonamjerne programe: viruse, trojance, ransomware i spyware. Svaki tip ima drugačiji način ulaska i cilj. Redovan backup i ažuran antivirus su dobra prva linija odbrane.",
    gameData: {
      vrijemeSekundi: 40,
      pitanja: [
        {
          tekst: "Ransomware šifruje tvoje fajlove i traži...",
          opcije: ["Korisničko ime", "Otkupninu u novcu", "Telefonski broj", "Email adresu"],
          tacno: 1,
        },
        {
          tekst: "Koja ekstenzija fajla je NAJOPASNIJA od nepoznatog pošiljaoca?",
          opcije: [".pdf", ".txt", ".exe", ".jpg"],
          tacno: 2,
        },
        {
          tekst: "Trojanac je program koji...",
          opcije: ["Pomaže ubrzati računar", "Izgleda korisno ali tajno šteti", "Čisti viruse", "Ubrzava internet"],
          tacno: 1,
        },
        {
          tekst: "Ako dobiješ ransomware, šta ODMAH treba da uradiš?",
          opcije: ["Platiti otkupninu", "Formatirati disk", "Isključiti uređaj iz mreže", "Restartovati računar"],
          tacno: 2,
        },
      ],
    },
    correctData: { tacni: [1, 2, 1, 2] },
  },

  // ═══════════════════════════════════════════════════════════════════
  // 5. JAVNI WIFI
  // ═══════════════════════════════════════════════════════════════════
  {
    topicSlug: "javni-wifi",
    title: "Šta je bezbjedno na javnom Wi-Fi-ju?",
    interactionType: "razvrstaj",
    difficulty: "easy",
    xp: 55,
    order: 1,
    tekst: "Sjediš u kafiću na javnom Wi-Fi-ju. Šta možeš raditi bezbjedno, a šta treba izbjegavati?",
    hint: "Na javnom Wi-Fi-ju neko može pokušati da vidi ili presretne podatke koje šalješ.",
    objasnjenje: "Na javnom Wi-Fi-ju napadač može presretati saobraćaj (man-in-the-middle napad). Aktivnosti bez osjetljivih podataka su manje rizične. Za bankarstvo i prijave koristi mobilne podatke ili VPN.",
    gameData: {
      stavke: [
        { id: "s1", tekst: "Čitanje vijesti na HTTPS sajtovima" },
        { id: "s2", tekst: "Prijava na internet bankarstvo" },
        { id: "s3", tekst: "Gledanje YouTube videa" },
        { id: "s4", tekst: "Kupovina online kreditnom karticom" },
        { id: "s5", tekst: "Provjera rasporeda javnog prevoza" },
        { id: "s6", tekst: "Slanje lozinke kolegi putem emaila" },
      ],
      kante: [
        { id: "sigurno", naziv: "OK za javni Wi-Fi ✓" },
        { id: "rizicno", naziv: "Izbjegavaj na javnom Wi-Fi ✗" },
      ],
    },
    correctData: {
      sigurno: ["s1", "s3", "s5"],
      rizicno: ["s2", "s4", "s6"],
    },
  },
  {
    topicSlug: "javni-wifi",
    title: "Podesi Wi-Fi zaštitu",
    interactionType: "podesi",
    difficulty: "medium",
    xp: 65,
    order: 2,
    tekst: "Postavi bezbjedne Wi-Fi opcije na svom uređaju.",
    hint: "Što manje uređaj automatski dijeli, to je manji rizik.",
    objasnjenje: "Automatsko spajanje na otvorene mreže je rizično — uređaj se može spojiti na lažnu 'honeypot' mrežu bez tvog znanja. VPN šifruje saobraćaj i na nesigurnoj mreži. Dijeljenje fajlova na javnoj mreži otvara uređaj napadačima.",
    gameData: {
      uputstvo: "Postavi bezbjedne Wi-Fi opcije.",
      opcije: [
        { id: "o1", naziv: "Automatsko spajanje na otvorene mreže", opis: "Automatski se spaja na sve dostupne Wi-Fi mreže", ikona: "📶", tacnoStanje: false },
        { id: "o2", naziv: "VPN na javnom Wi-Fi-ju", opis: "Šifruje saobraćaj na javnim mrežama", ikona: "🔒", tacnoStanje: true },
        { id: "o3", naziv: "Dijeljenje datoteka", opis: "Drugi uređaji na mreži mogu pristupiti tvojim fajlovima", ikona: "📁", tacnoStanje: false },
        { id: "o4", naziv: "Firewall aktivan", opis: "Štiti od neovlašćenog pristupa", ikona: "🛡️", tacnoStanje: true },
      ],
    },
    correctData: { ukljuceno: ["o2", "o4"], iskljuceno: ["o1", "o3"] },
  },
  {
    topicSlug: "javni-wifi",
    title: "Bankarstvo u kafiću",
    interactionType: "odluka",
    difficulty: "easy",
    xp: 50,
    order: 3,
    tekst: "Sjediš u kafiću i treba hitno da napraviš uplatu. Koja je najbezbjednija opcija?",
    hint: "Koji od ovih načina ne prolazi kroz nesigurnu mrežu kafića?",
    objasnjenje: "Mobilni podaci (4G/5G) su šifrovani i ne prolaze kroz lokalnu Wi-Fi mrežu, pa su bezbjedniji za bankarstvo. VPN na javnom Wi-Fi-ju je prihvatljiva alternativa. Otvoreni Wi-Fi bez VPN-a je rizičan za osjetljive transakcije.",
    gameData: {
      opcije: [
        { id: "a", tekst: "Koristim kafićev Wi-Fi — ionako je HTTPS" },
        { id: "b", tekst: "Čekam da dođem kući" },
        { id: "c", tekst: "Koristim mobilne podatke (4G/5G)" },
        { id: "d", tekst: "Tražim od konobara Wi-Fi lozinku — zaštićena mreža je dovoljna" },
      ],
    },
    correctData: { id: "c" },
  },

  // ═══════════════════════════════════════════════════════════════════
  // 6. DVOFAKTORSKA
  // ═══════════════════════════════════════════════════════════════════
  {
    topicSlug: "dvofaktorska",
    title: "Postavi 2FA na nalog",
    interactionType: "podesi",
    difficulty: "easy",
    xp: 60,
    order: 1,
    tekst: "Podešavaš zaštitu svog email naloga. Postavi opcije ispravno.",
    hint: "2FA i automatska ažuriranja su uvijek dobri. 'Zapamti uređaj zauvijek' je rizično.",
    objasnjenje: "2FA dodaje drugi sloj zaštite — i ako neko sazna lozinku, ne može ući bez drugog faktora. Authenticator app je bezbjedniji od SMS-a jer ne zavisi od mobilne mreže. 'Zapamti zauvijek' znači da svako ko uzme uređaj može pristupiti nalogu.",
    gameData: {
      uputstvo: "Postavi bezbjednu autentifikaciju na nalog.",
      opcije: [
        { id: "o1", naziv: "Dvofaktorska autentifikacija", opis: "Dodatni sloj zaštite pri svakoj prijavi", ikona: "🔐", tacnoStanje: true },
        { id: "o2", naziv: "Authenticator app kao 2FA", opis: "Bezbjedniji od SMS-a i ne traži internet", ikona: "📱", tacnoStanje: true },
        { id: "o3", naziv: "Zapamti ovaj uređaj zauvijek", opis: "Ne traži 2FA na ovom uređaju više nikad", ikona: "💾", tacnoStanje: false },
        { id: "o4", naziv: "Automatska ažuriranja aplikacije", opis: "Ažurna verzija znači zakrpljene propuste", ikona: "🔄", tacnoStanje: true },
      ],
    },
    correctData: { ukljuceno: ["o1", "o2", "o4"], iskljuceno: ["o3"] },
  },
  {
    topicSlug: "dvofaktorska",
    title: "SMS ili Authenticator?",
    interactionType: "odluka",
    difficulty: "medium",
    xp: 65,
    order: 2,
    tekst: "Koji oblik dvofaktorske autentifikacije je NAJSIGURNIJI?",
    hint: "Šta može presresti SMS? Šta ne može?",
    objasnjenje: "SMS 2FA može biti ugrožen SIM swapping napadom, kada napadač prevari operatera da prebaci tvoj broj. Authenticator app generiše kodove na uređaju, pa nema SMS poruke koju neko može presresti. Hardware ključevi poput YubiKey su najjači, ali Authenticator app je odličan izbor za većinu korisnika.",
    gameData: {
      opcije: [
        { id: "a", tekst: "SMS kod na mobilni" },
        { id: "b", tekst: "Authenticator aplikacija (Google/Microsoft Authenticator)" },
        { id: "c", tekst: "Email potvrda" },
        { id: "d", tekst: "Bezbjednosno pitanje" },
      ],
    },
    correctData: { id: "b" },
  },
  {
    topicSlug: "dvofaktorska",
    title: "Neko traži 2FA kod",
    interactionType: "razgovor",
    difficulty: "medium",
    xp: 75,
    order: 3,
    tekst: "Dobio/la si poruku. Odaberi pravi odgovor!",
    hint: "Legitimna podrška NIKAD ne traži 2FA kodove ili lozinke.",
    objasnjenje: "2FA kodovi su jednokratni i tajni. Svaka osoba koja od tebe traži taj kod — bez obzira na to kako se predstavlja — pokušava preuzeti tvoj nalog. Legitimna kompanija NIKAD ne traži kod koji si dobio/la.",
    gameData: {
      kontekst: "Primio/la si ovu poruku na Instagramu:",
      poruke: [
        { od: "bot", tekst: "Hej! Ja sam Ana iz Instagram tima za podršku. Primijetili smo sumnjive aktivnosti na tvom nalogu. Treba mi samo verifikacioni kod koji ti sada dolazi SMS-om da potvrdimo identitet." },
        {
          od: "player",
          opcije: [
            { id: "a", tekst: "Ok, čekam kod pa ti šaljem.", tip: "lose" },
            { id: "b", tekst: "Legitimna podrška ne traži kodove. Ovo je prevara — blokiram te.", tip: "win" },
            { id: "c", tekst: "A zašto ti treba kod? Objasni mi.", tip: "neutral" },
          ],
        },
      ],
    },
    correctData: { tacnoId: "b" },
  },

  // ═══════════════════════════════════════════════════════════════════
  // 7. SOCIJALNI INŽENJERING
  // ═══════════════════════════════════════════════════════════════════
  {
    topicSlug: "socijalni-inzenjering",
    title: "Lažna IT podrška",
    interactionType: "razgovor",
    difficulty: "medium",
    xp: 75,
    order: 1,
    tekst: "Zove te nepoznata osoba. Odaberi kako ćeš odgovoriti.",
    hint: "Pravi IT timovi nikad ne traže lozinke — imaju drugi pristup sistemu.",
    objasnjenje: "Vishing (voice phishing) je napad telefonom u kojem napadač glumi IT podršku, banku ili službu za hitne slučajeve. Pravi IT tim ne treba tvoju lozinku — ima druge načine za rad na sistemu. Završi poziv i nazovi zvaničan broj firme.",
    gameData: {
      kontekst: "Telefon zvoni. Nepoznati glas:",
      poruke: [
        { od: "bot", tekst: "Dobar dan, zovem iz IT odjela vaše firme. Primijetili smo da vaš računar šalje sumnjive podatke na mrežu. Hitno mi treba vaša Windows lozinka da pristupimo uređaju i riješimo problem." },
        {
          od: "player",
          opcije: [
            { id: "a", tekst: "Dati im lozinku — zvuče legitimno i ozbiljno.", tip: "lose" },
            { id: "b", tekst: "Reći da ću prekinuti poziv i nazvati IT odjel na zvaničnom broju.", tip: "win" },
            { id: "c", tekst: "Pitati za njihov ID broj pa onda odlučiti.", tip: "neutral" },
          ],
        },
      ],
    },
    correctData: { tacnoId: "b" },
  },
  {
    topicSlug: "socijalni-inzenjering",
    title: "SMS od banke?",
    interactionType: "phishing_inbox",
    difficulty: "medium",
    xp: 70,
    order: 2,
    tekst: "Primio/la si SMS poruku. Tapni sve crvene zastavice!",
    hint: "Pažljivo provjeri link, pošiljaoca i ton poruke.",
    objasnjenje: "Smishing (SMS phishing) je sve češći jer smo navikli vjerovati SMS-ovima. Banka nikad ne šalje SMS-om link da uneseš podatke — koristi svoju zvaničnu aplikaciju ili web stranicu. Svaki SMS koji traži hitnu akciju s linkom je sumnjiv.",
    gameData: {
      od: "Banka",
      naslov: "SMS poruka",
      tijelo: "HITNO: Vaša debitna kartica je BLOKIRANA zbog sumnjive transakcije od 847 €! Da deblokirate karticu kliknite ODMAH: http://banka-verify.tk/deblok i unesite podatke kartice. Rok: 2 sata!",
      link: "http://banka-verify.tk/deblok",
      zastavice: [
        { id: "z1", tekst: "Lažni domen u linku (.tk nije domen banke)", element: "link" },
        { id: "z2", tekst: "Vještačka hitnost i prijetnja (2 sata!)", element: "tijelo" },
        { id: "z3", tekst: "Traži unos podataka kartice putem linka", element: "tijelo" },
        { id: "z4", tekst: "Iznos transakcije je specifičan da stvori paniku", element: "tijelo" },
      ],
    },
    correctData: { ids: ["z1", "z2", "z3", "z4"] },
  },
  {
    topicSlug: "socijalni-inzenjering",
    title: "Prijatelj u nevolji",
    interactionType: "odluka",
    difficulty: "easy",
    xp: 55,
    order: 3,
    tekst: "Primio/la si poruku na Viberu: 'Hej, ja sam tvoj brat Marko. Izgubio sam novčanik. Pošalji mi hitno 100 € na ovaj broj...' Šta radiš?",
    hint: "Može li nalog biti kompromitovan? Kako provjeravaš da je to zaista brat?",
    objasnjenje: "Napadači kompromituju naloge i šalju poruke svim kontaktima, računajući na paniku i hitnost. Najvažniji korak je provjera identiteta kroz kanal koji kontrolišeš — nazovi brata direktno. Nikad ne šalji novac samo na osnovu poruke.",
    gameData: {
      opcije: [
        { id: "a", tekst: "Odmah pošaljem novac — brat je u nevolji!" },
        { id: "b", tekst: "Pitam ga nešto što samo brat zna" },
        { id: "c", tekst: "Nazovem brata direktno na poznati broj" },
        { id: "d", tekst: "Ignorišem poruku" },
      ],
    },
    correctData: { id: "c" },
  },

  // ═══════════════════════════════════════════════════════════════════
  // 8. PREVARE
  // ═══════════════════════════════════════════════════════════════════
  {
    topicSlug: "prevare",
    title: "Nagradna igra na Facebooku",
    interactionType: "razgovor",
    difficulty: "easy",
    xp: 55,
    order: 1,
    tekst: "Dobio/la si poruku. Odaberi odgovor!",
    hint: "Legitimne nagradne igre ne traže uplatu niti lične podatke putem poruke.",
    objasnjenje: "Prevare s nagradama obično imaju istu strukturu: 'dobio/la si', ali moraš nešto platiti ili poslati podatke da preuzmeš nagradu. Legitiman dobitnik ne plaća ništa da bi dobio nagradu. Tipični znakovi su čudni 'sponzori', hitnost i zahtjev za podacima.",
    gameData: {
      kontekst: "Primio/la si ovu poruku na Facebooku:",
      poruke: [
        { od: "bot", tekst: "Čestitamo! 🎉 Izabrani ste kao dobitnik iPhone-a 15 u nagradnoj igri koju sponzoriše Apple! Da preuzmete nagradu, treba da platite poštarinu od 15 € i pošaljete nam ličnu kartu radi potvrde identiteta." },
        {
          od: "player",
          opcije: [
            { id: "a", tekst: "Platim poštarinu — 15 € je malo za iPhone!", tip: "lose" },
            { id: "b", tekst: "Ovo je prevara — blokiram profil i prijavim Facebooku.", tip: "win" },
            { id: "c", tekst: "Pitam da mi pošalju više detalja o nagradnoj igri.", tip: "neutral" },
          ],
        },
      ],
    },
    correctData: { tacnoId: "b" },
  },
  {
    topicSlug: "prevare",
    title: "Prava ili lažna online prodavnica?",
    interactionType: "pravo_lazno",
    difficulty: "medium",
    xp: 65,
    order: 2,
    tekst: "Tražiš Nike patike online. Koja od ovih web stranica je legitimna?",
    hint: "Pažljivo pogledaj domen, cijenu i dizajn stranice.",
    objasnjenje: "Lažne prodavnice imitiraju dizajn poznatih brendova, ali koriste sumnjive domene i nude nerealno niske cijene da bi privukle kupce. Uvijek kupuj direktno sa zvanične stranice ili kod provjerenih prodavaca. Ako cijena zvuči previše dobro — vjerovatno je prevara.",
    gameData: {
      tip: "url",
      uputstvo: "Koja od ovih stranica je legitimna prodavnica?",
      a: { tekst: "https://www.nike.com/ba (Nike zvanični sajt, cijena 150 €)", oznaka: "A" },
      b: { tekst: "http://nike-outlet-shop.tk (Nike MEGA RASPRODAJA, patike 15 €!)", oznaka: "B" },
    },
    correctData: { tacno: "a" },
  },
  {
    topicSlug: "prevare",
    title: "Crypto investicija",
    interactionType: "odluka",
    difficulty: "medium",
    xp: 65,
    order: 3,
    tekst: "Na Instagramu ti se javlja 'influencer' i nudi garantovan prinos od 300% u kriptovalutama za 24 sata. Traži početnu uplatu od 100 €. Šta radiš?",
    hint: "Postoji li zakoniti finansijski instrument koji garantuje 300% prinos?",
    objasnjenje: "Crypto investicione prevare (Ponzi sheme, pump-and-dump) obećavaju nerealne prinose koji u praksi nisu održivi. 'Garantovana zarada' je uvijek crvena zastavica — tržišta ne garantuju ništa. Novac uplaćen u ovakve sheme rijetko se vraća. Prijavljivanje profila je odgovoran potez.",
    gameData: {
      opcije: [
        { id: "a", tekst: "Uplatim 100 € — 300% prinos zvuči odlično!" },
        { id: "b", tekst: "Pitam za detalje i referencije" },
        { id: "c", tekst: "Prepoznajem ovo kao Ponzi prevaru i prijavim profil" },
        { id: "d", tekst: "Uplatim manji iznos kao test" },
      ],
    },
    correctData: { id: "c" },
  },

  // ═══════════════════════════════════════════════════════════════════
  // 9. AŽURIRANJA
  // ═══════════════════════════════════════════════════════════════════
  {
    topicSlug: "azuriranja",
    title: "Postavi automatska ažuriranja",
    interactionType: "podesi",
    difficulty: "easy",
    xp: 55,
    order: 1,
    tekst: "Podesi sistem tako da se brzo štiti od poznatih ranjivosti.",
    hint: "Automatski je uvijek bolje od ručnog — ranjivosti se mogu iskoristiti u satima od objave.",
    objasnjenje: "Napadači često iskorišćavaju poznate ranjivosti odmah nakon objave bezbjednosnih ažuriranja, jer znaju da mnogi korisnici kasne. Automatska ažuriranja drže te korak ispred. Softver koji više nema podršku ne treba samo ažurirati — treba ga zamijeniti.",
    gameData: {
      uputstvo: "Postavi bezbjedne opcije ažuriranja sistema.",
      opcije: [
        { id: "o1", naziv: "Automatska ažuriranja OS-a", opis: "Sistem se automatski ažurira noću", ikona: "🔄", tacnoStanje: true },
        { id: "o2", naziv: "Automatska ažuriranja aplikacija", opis: "Aplikacije se ažuriraju bez posebnog odobrenja", ikona: "📱", tacnoStanje: true },
        { id: "o3", naziv: "Odgodi ažuriranja za 30 dana", opis: "Čekaš 30 dana prije instalacije", ikona: "⏱️", tacnoStanje: false },
        { id: "o4", naziv: "Obavještenja o ažuriranjima", opis: "Prima obavještenja kada su ažuriranja dostupna", ikona: "🔔", tacnoStanje: true },
      ],
    },
    correctData: { ukljuceno: ["o1", "o2", "o4"], iskljuceno: ["o3"] },
  },
  {
    topicSlug: "azuriranja",
    title: "Zanemariti bezbjednosno ažuriranje?",
    interactionType: "odluka",
    difficulty: "easy",
    xp: 50,
    order: 2,
    tekst: "Tvoj laptop traži hitno bezbjednosno ažuriranje zbog kritične ranjivosti. Traje 10 minuta. Šta radiš?",
    hint: "Koliko brzo napadači iskorišćavaju poznate ranjivosti nakon objave zakrpe?",
    objasnjenje: "Bezbjednosna ažuriranja se objavljuju zato što je ranjivost otkrivena — i napadači to znaju odmah. 'Exploit race' počinje istog dana: napadači razvijaju napade dok korisnici odgađaju ažuriranje. Deset minuta za zakrpu je uvijek dobra odluka.",
    gameData: {
      opcije: [
        { id: "a", tekst: "Zanemarim notifikaciju — ažurirati mogu i sutra" },
        { id: "b", tekst: "Odaberem 'Podsjeti me za 7 dana'" },
        { id: "c", tekst: "Ažuriram odmah — 10 minuta nije puno" },
        { id: "d", tekst: "Deaktiviram automatska ažuriranja — smetaju mi" },
      ],
    },
    correctData: { id: "c" },
  },
  {
    topicSlug: "azuriranja",
    title: "Brzi test: Ažuriranja",
    interactionType: "brzi_krug",
    difficulty: "easy",
    xp: 65,
    order: 3,
    tekst: "Brzi krug o ažuriranjima! Imaš 35 sekundi.",
    hint: "Ažuriranja nisu samo nove funkcije — često su najvažnije bezbjednosne zakrpe.",
    objasnjenje: "Ažuriranja softvera su važna za bezbjednost jer zatvaraju poznate ranjivosti. Najbezbjedniji korisnici su oni koji ažuriraju brzo i, gdje je moguće, automatski.",
    gameData: {
      vrijemeSekundi: 35,
      pitanja: [
        {
          tekst: "Zašto su bezbjednosna ažuriranja važna?",
          opcije: ["Dodaju nove funkcije", "Krpe bezbjednosne rupe", "Ubrzavaju računar", "Štede bateriju"],
          tacno: 1,
        },
        {
          tekst: "Koliko brzo treba primijeniti kritično bezbjednosno ažuriranje?",
          opcije: ["U roku od godine", "Što prije moguće", "Nije bitno", "Nakon sedam dana"],
          tacno: 1,
        },
        {
          tekst: "Koji softver je NAJVAŽNIJE redovno ažurirati?",
          opcije: ["Igrice", "Operativni sistem i pregledač", "Pozadinska slika", "Čuvar ekrana"],
          tacno: 1,
        },
      ],
    },
    correctData: { tacni: [1, 1, 1] },
  },

  // ═══════════════════════════════════════════════════════════════════
  // 10. SIGURNO PREUZIMANJE
  // ═══════════════════════════════════════════════════════════════════
  {
    topicSlug: "sigurno-preuzimanje",
    title: "Preuzeti softver s foruma?",
    interactionType: "odluka",
    difficulty: "easy",
    xp: 50,
    order: 1,
    tekst: "Treba ti besplatan program za uređivanje fotografija. Na forumu vidiš 'crack' verziju skupog softvera. Šta radiš?",
    hint: "Zašto bi neko 'besplatno' dijelio softver koji košta 200 €?",
    objasnjenje: "Piratski softver (cracks, keygens) je jedan od najčešćih načina širenja malwarea. Osoba koja dijeli crack zapravo distribuira zaraženi fajl. Postoji mnoštvo legitimnih besplatnih alternativa (GIMP umjesto Photoshop, VLC za medije). Uvijek koristi zvaničan izvor.",
    gameData: {
      opcije: [
        { id: "a", tekst: "Preuzmem crack — besplatno je i znam koristiti antivirus" },
        { id: "b", tekst: "Tražim legitimnu besplatnu alternativu (npr. GIMP)" },
        { id: "c", tekst: "Platim pravu licencu softvera" },
        { id: "d", tekst: "Preuzmem i skeniram antivirusom pa vidim" },
      ],
    },
    correctData: { id: "b" },
  },
  {
    topicSlug: "sigurno-preuzimanje",
    title: "Bezbjedni ili rizični izvori",
    interactionType: "razvrstaj",
    difficulty: "medium",
    xp: 65,
    order: 2,
    tekst: "Razvrstaj izvore preuzimanja na bezbjedne i rizične.",
    hint: "Zvanični izvori imaju recenzije, potpisane aplikacije i sisteme provjere.",
    objasnjenje: "Zvanične prodavnice i stranice proizvođača provjeravaju aplikacije. Treće strane i torrent sajtovi nemaju takvu kontrolu — malware se tamo mnogo lakše širi. Čak i na Google Play-u može proći loša aplikacija, ali je rizik daleko manji nego na nepoznatim izvorima.",
    gameData: {
      stavke: [
        { id: "s1", tekst: "Apple App Store" },
        { id: "s2", tekst: "Torrent sajt" },
        { id: "s3", tekst: "Zvanična stranica Mozilla (za Firefox)" },
        { id: "s4", tekst: "APK fajl s Telegrama" },
        { id: "s5", tekst: "Google Play Store" },
        { id: "s6", tekst: "Warez forum" },
      ],
      kante: [
        { id: "sigurno", naziv: "Bezbjedan izvor ✓" },
        { id: "rizicno", naziv: "Rizičan izvor ✗" },
      ],
    },
    correctData: {
      sigurno: ["s1", "s3", "s5"],
      rizicno: ["s2", "s4", "s6"],
    },
  },
  {
    topicSlug: "sigurno-preuzimanje",
    title: "Pravi ili lažni Google Play?",
    interactionType: "pravo_lazno",
    difficulty: "medium",
    xp: 65,
    order: 3,
    tekst: "Tražiš gdje preuzeti aplikaciju. Koja od ove dvije opcije je legitimni Google Play?",
    hint: "Pazi na domen i dizajn — lažni Google Play sajtovi su često savršene kopije.",
    objasnjenje: "Lažni app store sajtovi su dizajnirani da izgledaju identično kao originalni. Jedina pouzdana provjera je domen: pravi Google Play je isključivo play.google.com. Svaki drugi domen je lažan, bez obzira na to koliko identično izgleda. Na telefonu — uvijek koristi ugrađenu Play Store aplikaciju.",
    gameData: {
      tip: "url",
      uputstvo: "Koji link vodi na pravi Google Play?",
      a: { tekst: "https://play.google.com/store/apps", oznaka: "A" },
      b: { tekst: "https://google-play-store.download/apps", oznaka: "B" },
    },
    correctData: { tacno: "a" },
  },
];
